---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/static-golang
    tag: 'latest'

inputs:
- name: travis-resource-git
output:
- name: built-resource
run:
  path: travis-resource-git/bin/ci
