resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
resources:
  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack-url}}
  - name: travis-resource-git
    type: git
    source:
      uri: https://github.com/Orange-OpenSource/travis-resource.git
      branch: master
  - name: travis-resource-image
    type: docker-image
    source:
      email: {{docker-hub-email}}
      username: {{docker-hub-username}}
      password: {{docker-hub-password}}
      repository: {{docker-hub-image}}
jobs:
  - name: publish-travis-resource-image
    public: true
    serial: true
    plan:
    - get: travis-resource-git
      trigger: true
    - task: build-resource
      file: travis-resource-git/build.yml
      on_failure:
        put: slack-alert
        params:
          text_file: notif-resource/output-ci.txt
          text: |
            Pipeline $BUILD_PIPELINE_NAME with build $BUILD_NAME failed, see: $ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

            Result: $TEXT_FILE_CONTENT
          channel: {{slack-channel}}
          username: {{slack-username}}
    - put: travis-resource-image
      params:
        build: built-resource/
    - put: slack-alert
      params:
        text: "Pipeline $BUILD_PIPELINE_NAME with build $BUILD_NAME passed, see: $ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
        channel: {{slack-channel}}
        username: {{slack-username}}