---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/static-golang
    tag: 'latest'

inputs:
- name: travis-resource-git
outputs:
- name: built-resource
- name: notif-resource
run:
  path: travis-resource-git/bin/run_ci
